### ISSUE TITLE
[RC] Laplacian Smoothing Gradient Descent [By41BjA9YQ]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#103]
| Team Name | Affiliation |
|---|---|
| Sharks. | Epfl; Epfl; Epfl |

 - Paper: [Laplacian Smoothing Gradient Descent](https://openreview.net/pdf?id=By41BjA9YQ)
 - Forum: [Comments](https://openreview.net/forum?id=By41BjA9YQ)

**Comment by MohammadHossein-Bahari** [comment]
Close
