### ISSUE TITLE
[RC] 3D-RelNet: Joint Object and Relational Network for 3D Prediction [rygk9oA9Ym]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#38]
| Team Name | Affiliation |
|---|---|
| Narwhal | University of Waterloo |

 - Paper: [3D-RelNet: Joint Object and Relational Network for 3D Prediction](https://openreview.net/pdf?id=rygk9oA9Ym)
 - Forum: [Comments](https://openreview.net/forum?id=rygk9oA9Ym)

**Comment by KP-Kepra** [comment]
@reproducibility-org close
