### ISSUE TITLE
[RC] Efficient Exploration through Bayesian Deep Q-Networks [B1e7hs05Km]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#56]
| Team Name | Affiliation |
|---|---|
| 2Young | UCI |

 - Paper: [Efficient Exploration through Bayesian Deep Q-Networks](https://openreview.net/pdf?id=B1e7hs05Km)
 - Forum: [Comments](https://openreview.net/forum?id=B1e7hs05Km)

**Comment by Guyanqi** [comment]
Closes #56

**Comment by Guyanqi** [comment]
@reproducibility-org close
