### ISSUE TITLE
[RC] Perfect Match: A Simple Method for Learning Representations For Counterfactual Inference With Neural Networks [rkxt8oC9FQ]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#66]
| Team Name | Affiliation |
|---|---|
| ZAHO | McGill University |

 - Paper: [Perfect Match: A Simple Method for Learning Representations For Counterfactual Inference With Neural Networks](https://openreview.net/pdf?id=rkxt8oC9FQ)
 - Forum: [Comments](https://openreview.net/forum?id=rkxt8oC9FQ)

**Comment by siauc1** [comment]
@reproducibility-org close
