### ISSUE TITLE
[RC] MULTI-SCALE STACKED HOURGLASS NETWORK FOR HUMAN POSE ESTIMATION [HkM3vjCcF7]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#68]
| Team Name | Affiliation |
|---|---|
| The Hilarious Crocodiles | Carnegie Mellon University;Carnegie Mellon University;Carnegie Mellon University |

 - Paper: [MULTI-SCALE STACKED HOURGLASS NETWORK FOR HUMAN POSE ESTIMATION](https://openreview.net/pdf?id=HkM3vjCcF7)
 - Forum: [Comments](https://openreview.net/forum?id=HkM3vjCcF7)

**Comment by dsanders-cmu** [comment]
@reproducibility-org close
