### ISSUE TITLE
[RC] TEXT EMBEDDINGS FOR RETRIEVAL FROM A LARGE KNOWLEDGE BASE [HyleYiC9FX]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#8]
| Team Name | Affiliation |
|---|---|
| HyperFury | Individual Contributor |

 - Paper: [TEXT EMBEDDINGS FOR RETRIEVAL FROM A LARGE KNOWLEDGE BASE](https://openreview.net/pdf?id=HyleYiC9FX)
 - Forum: [Comments](https://openreview.net/forum?id=HyleYiC9FX)

**Comment by korkinof** [comment]
@reproducibility-org close
