### ISSUE TITLE
[RC] Shallow Learning For Deep Networks [r1Gsk3R9Fm]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#81]
| Team Name | Affiliation |
|---|---|
| Data Wizards | Swiss Federal Institute of Technology Lausanne (EPFL); EPFL, Technical University of Denmark (DTU); EPFL, DTU |

 - Paper: [Shallow Learning For Deep Networks](https://openreview.net/pdf?id=r1Gsk3R9Fm)
 - Forum: [Comments](https://openreview.net/forum?id=r1Gsk3R9Fm)

**Comment by dogatekin** [comment]
@reproducibility-org close
