### ISSUE TITLE
[RC] Auxiliary Variational MCMC [r1NJqsRctX]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#88]
| Team Name | Affiliation |
|---|---|
| EPFL_ML | EPFL,IIT Kanpur; EPFL, IIT Kanpur; EPFL,  |

 - Paper: [Auxiliary Variational MCMC](https://openreview.net/pdf?id=r1NJqsRctX)
 - Forum: [Comments](https://openreview.net/forum?id=r1NJqsRctX)

**Comment by kishinmh** [comment]
@reproducibility-org close

**Comment by kishinmh** [comment]
@reproducibility-org close
