### ISSUE TITLE
[RC] TequilaGAN: How To Easily Identify GAN Samples [Bkl2SjCcKQ]

### ISSUE THREAD

**Issue by reproducibility-org** [reproducibility-challenge/iclr_2019#92]
| Team Name | Affiliation |
|---|---|
| Sharks | epfl; epfl; epfl |

 - Paper: [TequilaGAN: How To Easily Identify GAN Samples](https://openreview.net/pdf?id=Bkl2SjCcKQ)
 - Forum: [Comments](https://openreview.net/forum?id=Bkl2SjCcKQ)

**Comment by SaeedSaadatnejad** [comment]
close
